### ISSUE TITLE
rename dg.org.eclipse.jdt.ls.decompiler.fernflower.tests to dg.jdt.ls.decompiler.fernflower.tests

### ISSUE THREAD

**Issue by fbricon** [dgileadi/dg.jdt.ls.decompiler#1]
please avoid using org.eclipse namespaces to steer clear of trademark issues

**Comment by dgileadi** [comment]
Fixed by c50baa31.

**Comment by fbricon** [comment]
you still have a zombie dir https://github.com/dgileadi/dg.jdt.ls.decompiler/tree/master/dg.org.eclipse.jdt.ls.decompiler.fernflower.tests/target/classes

**Comment by dgileadi** [comment]
Wow, I'm really bad at this renaming stuff. Hopefully fixed now.
